version: '3.9'

volumes:
  postgres_data: {}

services:
  database.epilepsy_portal:
    image: postgres:9
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend.epilepsy_portal:
    build: .
    image: epilepsy_portal
    tty: true
    environment:
      # Flip to 'production' for AWS deployments
      - ENVIRONMENT=local
      - DJANGO_SETTINGS_MODULE=epilepsy_portal.settings.base
      - PYTHONBUFFERED=1
    volumes:
      - .:/backend
    depends_on:
      - database.epilepsy_portal